### ISSUE TITLE
ImportError: No module named gflags

### ISSUE THREAD

**Issue by srustamo** [chmduquesne/michel#2]
```
❮ michel pull
Traceback (most recent call last):
  File "/usr/local/bin/michel", line 7, in <module>
    from michel.michel import main
  File "/usr/local/lib/python2.7/site-packages/michel/michel.py", line 11, in <module>
    import gflags
ImportError: No module named gflags

```
```
❯ pip2.7 install michel
Collecting michel
  Using cached michel-0.0.8.tar.gz
Collecting google-api-python-client (from michel)
  Using cached google_api_python_client-1.6.4-py2.py3-none-any.whl
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client->michel)
  Using cached uritemplate-3.0.0-py2.py3-none-any.whl
Collecting oauth2client<5.0.0dev,>=1.5.0 (from google-api-python-client->michel)
  Using cached oauth2client-4.1.2-py2.py3-none-any.whl
Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client->michel)
  Using cached httplib2-0.10.3.tar.gz
Requirement already satisfied: six<2dev,>=1.6.1 in /usr/local/lib/python2.7/site-packages (from google-api-python-client->michel)
Collecting pyasn1-modules>=0.0.5 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->michel)
  Using cached pyasn1_modules-0.2.1-py2.py3-none-any.whl
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->michel)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python2.7/site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->michel)
Building wheels for collected packages: michel, httplib2
  Running setup.py bdist_wheel for michel ... done
  Stored in directory: /Users/ba3/Library/Caches/pip/wheels/99/7a/01/7853b44fa7cf26d3a65f95e396ab0a5534c7e4621302327d3e
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: /Users/ba3/Library/Caches/pip/wheels/ca/ac/5f/749651f7925b231103f5316cacca82a487810c22d30f011c0c
Successfully built michel httplib2
Installing collected packages: uritemplate, pyasn1-modules, httplib2, oauth2client, google-api-python-client, michel
Successfully installed google-api-python-client-1.6.4 httplib2-0.10.3 michel-0.0.8 oauth2client-4.1.2 pyasn1-modules-0.2.1 uritemplate-3.0.0
```

**Comment by srustamo** [comment]
Installed gflags.
